config/routes.rb
BookmarkProject::Application.routes.draw do
resources :bookmarks
  
  match '/contact', :to => 'pages#contact'
  match '/bookmarks',   :to => 'bookmarks#bookmarks'
  match '/signup',    :to => 'users#new'
  match '/add', :to => 'bookmarks#new'
  match '/edit',    :to => 'bookmarks#edit'
  match '/show', :to => 'bookmarks#show'
  

  

  
  root :to => 'pages#home'

end

app/models/bookmark.rb
# == Schema Information
#
# Table name: bookmarks
#
#  id         :integer         not null, primary key
#  url        :string(255)
#  name       :string(255)
#  date       :date
#  created_at :datetime
#  updated_at :datetime
#

class Bookmark < ActiveRecord::Base
  
  attr_accessible :name, :url, :date
  
  	validates :url, 		:presence => true,
										:length   => { :minimum => 10 } 
	validates :name,  	:presence => true,
	                  :length   => { :maximum => 100 }

  
end

app/models/bookmarks.rb
# == Schema Information
#
# Table name: bookmarks
#
#  id         :integer         not null, primary key
#  url        :string(255)
#  name       :string(255)
#  date       :date
#  created_at :datetime
#  updated_at :datetime
#

class Bookmarks < ActiveRecord::Base
  attr_accessible :name, :url, :date
  
  	validates :url, 		:presence => true,
										:length   => { :minimum => 10 } 
										
	  validates :name,  	:presence => true,
	                  :length   => { :maximum => 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
    def index
     @title = "Index"
    @bookmarks = Bookmark.all
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
def bookmarks
     @title = "All Bookmarks"
    
    respond_to do |format|
      format.html # bookmarks.html.erb
    end
  end
  
    def new
      @title = "New"
   	 @bookmark = Bookmark.new
   	 respond_to do |format|
      format.html # new.html.erb
   end
   end
   
   def show
    @title = "Show"
	@bookmark = Bookmark.find(params[:id])
   	 respond_to do |format|
      format.html # new.html.erb  
   end
 end  
 
   # GET /bookmarks/1/edit
   def edit
      @title = "Edit"
      @bookmark = Bookmark.find(params[:id])
   end



   def create
   	 @bookmark = Bookmark.new(params[:bookmark])

     if @bookmark.save
        redirect_to(@bookmark, :notice => 'Bookmark was successfully created.') 
    else
         render :action => "new" 
   end
   end


   def update
   	 @bookmark = Bookmark.find(params[:id])
   	     respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
      	 format.html { redirect_to(@bookmark, :notice => 'Bookmark was successfully updated.') }
      else
         format.html { render :action => "edit" }
      end
   end
 end


  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to(bookmarks_url) }

    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def bookmarks
    @title = "Bookmarks"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign Up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Ruby on Rails Bookmark Project"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  
  def hinted_text_field_tag(name, value = nil, hint = "Click and enter text", options={})
  value = value.nil? ? hint : value
  text_field_tag name, value, {:onclick => "if($(this).value == '#{hint}'){$(this).value = ''}", :onblur => "if($(this).value == ''){$(this).value = '#{hint}'}" }.update(options.stringify_keys)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_form.html.erb
  <div class="group">
    <%= f.label :url, t("activerecord.attributes.bookmark.url", :default => "Url"), :class => :label %>
    <%= f.text_field :url, :class => 'text_field' %>
    <span class="description">Ex: www.abc.com</span>
    
  </div>

  <div class="group">
    <%= f.label :name, t("activerecord.attributes.bookmark.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :date, t("activerecord.attributes.bookmark.date_saved", :default => "Date saved"), :class => :label %>
    <%= f.text_field :date, :class => 'text_field' %>
    <span class="description">Ex: 01/02/2010</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), bookmarks_path, :class => "text_button_padding link_button" %>
</div>

app/views/bookmarks/bookmarks.html.erb
<div class="content">            
	 <h2 class="title"><%= t("web-app-theme.all", :default => "New")  %> New</h2>
    <div class="inner">
      <!-- ------------- -->
      
      <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
          
                              <th>
            <%= t("activerecord.attributes.bookmark.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
          
                    <th>
            <%= t("activerecord.attributes.bookmark.url", :default => t("activerecord.labels.url", :default => "Url")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @bookmarks.each do |bookmark| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= bookmark.id %>
          </td>
          <td>
            <%= bookmark.name %>
          </td>
                    <td>
            <%= link_to bookmark.url, bookmarks_path(bookmark) %>
          </td>
                    <td>
            <%= bookmark.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", "#" %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", "#" %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", "#", :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
      
      <!-- ------------ -->
    </div>
  </div>

app/views/bookmarks/edit.html.erb
       
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Bookmark</h2>
    <div class="inner">
      <%= form_for @bookmark, :url => bookmark_path(@bookmark), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>

app/views/bookmarks/index.html.erb
<div class="content">            
	 <h2 class="title"><%= t("web-app-theme.all", :default => "New")  %> New</h2>
    <div class="inner">
      <!-- ------------- -->
      
      <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
          
                              <th>
            <%= t("activerecord.attributes.bookmark.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
          
                    <th>
            <%= t("activerecord.attributes.bookmark.url", :default => t("activerecord.labels.url", :default => "Url")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Saved On")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @bookmarks.each do |bookmark| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= bookmark.id %>
          </td>
          <td>
            <%= bookmark.name %>
          </td>
                    <td>
            <%= link_to bookmark.url, bookmarks_path(bookmark) %>
          </td>
                    <td>
            <%= bookmark.date%>
          </td>
          <td class="last">
        <%= link_to "#{t("web-app-theme.show", :default => "Show")}", bookmark_path(bookmark) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_bookmark_path(bookmark) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", bookmark_path(bookmark), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
              </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
      
      <!-- ------------ -->
    </div>
  </div>

app/views/bookmarks/new.html.erb
<div class="content">            
	 <h2 class="title"><%= t("web-app-theme.all", :default => "New")  %> New</h2>
    <div class="inner">
      <%= form_for :bookmark, :url => bookmarks_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>

app/views/bookmarks/show.html.erb
      
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.bookmark.url", :default => t("activerecord.labels.url", :default => "Url")) %>:</b>
          <%= @bookmark.url %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.bookmark.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @bookmark.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.bookmark.date_saved", :default => t("activerecord.labels.date", :default => "Date saved")) %>:</b>
          <%= @bookmark.date %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_bookmark_path(@bookmark), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), bookmark_path(@bookmark), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>

app/views/layouts/_navigation.erb
<% if false %>
 

<% else %>
	<li><%= link_to 'Signup ', "#" %></li>
	<li><%= link_to 'Help', "#" %></li>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="block"> <!-- originally: class = block notice -->
  <h3>Project Notes</h3>
  <div class="content">
    <p>Student: DeLaina Siltman</p>
    <p>Class: Ruby on Rails</p>
    <p>Iteration: One</p>
  </div>
</div>
<div class="block">
  <h3>Helpful Links</h3>
  <ul class="navigation">
     <%= render 'layouts/navigation' %>
  </ul>
</div>  

<div class="block">
  <h3>Search</h3>
  <br />
  <ul class="navigation">
			<%= form_tag("#", :method => "get") do %>
				<%= hinted_text_field_tag :search, params[:search], "search terms", :size => 18 %> 
				<%= submit_tag("Find!") %>
			<% end %>
  </ul>

</div>  
<!-- TODO: this is  todo comment -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%=title %></title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/djime-cerulean/style", "web-app-theme/override", :cache => false %>
  <%= javascript_include_tag :defaults, :cache => false %> <!--changed from T to F for Heroku to work -->
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Palatable: A Bookmark Storing Site</a></h1>
      <div id="user-navigation">
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List All")}", bookmarks_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "Add New")}", add_path %></li>
      <li><%= link_to "Contact Us", contact_path %>
    </ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main"> 
      <div class="block">         
      	<%= yield %> <!-- renders each different page -->
      </div>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> DeLaina Siltman</p>
          <%= debug(params) if Rails.env.development? %>
            </div>      
        </div>
      </div>
      <div id="sidebar">

        <%= render 'layouts/sidebar' %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/pages/bookmarks.html.erb
<div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Bookmarks</h2>
  <%= yield %>
  </div>

app/views/pages/contact.html.erb
<div class="content"> 
<div class="inner">
    <h2 class="title">Contact Us</h2>
  <p>DeLaina Siltman</p>
  <p><a href="mailto:DSILTMAN@matcmadison.edu">DSILTMAN@matcmadison.edu</a></p>
  </div>
  </div>

app/views/pages/home.html.erb
  <div class="secondary-navigation">
  </div> 

<div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Home</h2>
  <%= yield %>
  </div>
  
 

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>